#! /bin/sh
# chkconfig: - 91 09
# description: HPI SNMP Subagent
# processname: hpiSubagent

### BEGIN INIT INFO
# Provides: openhpi-subagent
# Required-Start: $network net-snmp
# Required-Stop:  $network net-snmp
# Default-Start:  
# Default-Stop:   0 1 2 3 4 5 6
# Short-Description: Start HPI SNMP Subagent at boot time
# Description:    Enable HPI SNMP Subagent service
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/bin/hpiSubagent"
prog="openhpi-subagent"
config="/etc/snmp/hpiSubagent.conf"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    [ `id -u` -eq 0 ] || exit 4
    echo -n $"Starting $prog: "
    daemon $exec $OPTIONS
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    [ `id -u` -eq 0 ] || exit 4
    echo -n $"Stopping $prog: "
    killproc $exec
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -l $prog $exec
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
